### PR TITLE
make buttons have a cute and 🤭 ~quircky~ 💋 hover effect

### PR DESCRIPTION
**Pull request by n-tdi**

### CODE REVIEW

**Comment by n-tdi** [comment]
Dear esteemed members of the PR team,

I come to you today with a plea to merge my PR. Why, you may ask? Well, let me tell you - it's not just any ordinary PR. This PR is cute and quirky, just like me!

First of all, let's talk about the cuteness factor. My PR is like a little kitten - small, fluffy, and adorable. Just looking at it will bring a smile to your face and warm your heart. Who wouldn't want to merge something that makes them feel all warm and fuzzy inside?

But it's not just cute - it's also quirky. My PR is like a little bird that dances to its own beat. It doesn't conform to the usual standards, but that's what makes it unique and special. And who doesn't love something that's unique and special?

Now, I know what you might be thinking. "But cute and quirky doesn't necessarily mean it's good." Well, let me tell you - my PR is not just a pretty face. It's actually really useful and has some great functionality. It's like a Swiss Army knife - it can do a lot of different things, and it does them all really well. And isn't that the kind of PR you want to merge? Something that's not just good-looking, but also practical and efficient?

So, dear PR team, I implore you to consider merging my PR. Think of it as adopting a cute, quirky little pet that will bring you joy and functionality. And who knows - maybe it will even inspire you to be a little more cute and quirky yourself!

Thank you for your time and consideration.

Sincerely,
N-tdi

**Comment by rownox** [comment]
Denied, the code sucks too much.

**Comment by n-tdi** [comment]
Your honor, the code is only 5 lines.
```scss
transition: all 0.2s ease-in-out;
&:hover {
  cursor: pointer;
  transform: scale(105%) translateY(-5px);
}
```

I do not know if you have the ability to comment on code quality, judging by this:
image

**Comment by n-tdi** [comment]
Please keep in mind this is an eigth of your scss.

**Comment by rownox** [comment]
Too bad, it sucks too much

**Pull request closed without merging**
